version: '3'
services:
  localnet:
    image: "solanalabs/solana:stable"
    ports:
      - "8899:8899"
      - "8900:8900"
      - "9900:9900"
    environment:
      - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=info,solana_bpf_loader=debug,solana_rbpf=debug
