[package]
name = "stable-swap-sim"
version = "0.1.0"
authors = ["michaelhly <michaelhly@gmail.com>"]
description = "Simulations of the StableSwap invariant compared to Curve's reference implementation"
license = "Apache-2.0"
homepage = "https://saber.so"
repository = "https://github.com/saber-hq/stable-swap"
edition = "2018"
keywords = ["solana", "saber", "curve"]

[lib]
name = "sim"

[dependencies]
pyo3 = "0.15.1"
