name: Fuzz

on:
  schedule:
    - cron: "0 0,8,16 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: cargo install cargo-fuzz --vers "^0.8"
      - run: cargo fetch
        working-directory: ./fuzz
      - run: cargo fuzz run fuzz_test
