name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - name: Build
      run: ./do.sh build
    - name: Run unit tests
      run: ./do.sh test
    - name: Run e2e tests
      run: ./do.sh e2e-test
